### ISSUE TITLE
Unknown function validate_ip_address error when provisioning

### ISSUE THREAD

**Issue by fongd** [ftaeger/ftaeger-mailhog#1]
Looking for a (working!) alternative to MailCatcher, I installed the module and put the following into my manifest file as directed:

`include mailhog`

Provisioning the box from scratch gives me the following error:

`==> default: Error: Unknown function validate_ip_address at /tmp/vagrant-puppet/modules-21abfbb41470b5bda4d14b425504216b/mailhog/manifests/init.pp:84 on node web.dev`

I'm running Ubuntu 14.04.1 LTS, puppet 3.8.7.

**Comment by ftaeger** [comment]
Hi, this is the case if the puppetlabs-stdlib is missing. 

Just run a "puppet module install puppetlabs-stdlib" and it should run just fine.

**Comment by fongd** [comment]
Hi, yeah that's that I thought, but I already tried that and puppet tells me it's already installed:

vagrant@web:~$ puppet module install --target-dir /puppet/modules puppetlabs-stdlib
Notice: Preparing to install into /puppet/modules ...
Notice: Module puppetlabs-stdlib 4.8.0 is already installed.

**Comment by ftaeger** [comment]
Could you try to include stdlib with "include stdlib" in your manifest? 

Not sure puppet < 4.x will autoload stdlib.

**Comment by fongd** [comment]
I put the following into my manifest but am getting the same error:

```
  include stdlib
  include mailhog
```

**Comment by ftaeger** [comment]
Could you try to update stdlib to a newer version? 

Really strange. It does work for me without any issues since weeks now. 

As far as I can see you're using vagrant with puppet. So do I. So I know this works out of the box using one of the puppet-labs base-boxes for example. 

Could you do a verbose run on your vagrant setup and check the output? What OS are you using? What vagrant version? Vagrantfile?

**Comment by ftaeger** [comment]
Any update on this? Did you find the error? Anyone else having this issue? I can't reproduce it with my setup ...

**Comment by fongd** [comment]
Sorry, work got in the way of me trying to figure this out. However, the good news is that this problem appears to be resolved now. I only had to update puppetlabs-stdlib and MailHog appears to be working correctly now. I can at least access the web UI on port 8025. FWIW, I had been running stdlib 4.8.0 but updating to 4.12.0 seems to have fixed it. I left include stdlib in my manifest, although I'm not sure that's even necessary. I'll reprovision the VM and will let you know!

**Comment by fongd** [comment]
Yup, removed include include stdlib from my manifest. Looks like it's good to go!

**Comment by ftaeger** [comment]
I "fixed" the issue by updating the documentation. Seems like the "validate_ip_address" was introduced to stdlib on version 4.10.0 the 1st time. Sorry for this flaw.
