### ISSUE TITLE
Feature Request: Include mhsendmail

### ISSUE THREAD

**Issue by navarr** [ftaeger/ftaeger-mailhog#10]
https://github.com/mailhog/mhsendmail

**Comment by ftaeger** [comment]
Feel free to commit a push request ... I am not actively maintaining this module since I switched from puppet to ansible for all my work.

**Comment by navarr** [comment]
Fair enough - sadly I don't understand enough about puppet for it.

Perhaps re-open and add a `hacktoberfest` label in the hopes someone knowledgeable feels charitable?
