### ISSUE TITLE
Mailhog attempts to reinstall on each Vagrant up

### ISSUE THREAD

**Issue by ChrisWiegman** [ftaeger/ftaeger-mailhog#2]
On every provision the module re-downloads and re-installs Mailhog. This results in about an extra 60 seconds or so added to each provision. Is this done for a reason or can this be streamlined some?

**Comment by ftaeger** [comment]
Hi,

thanks for pointing this out. I've updated the module to version 1.0.9 and uploaded it to the forge. Could you give this a try and check if it's running as expected now? 

Beware: You will need to update stdlib and the wget package as well as there have been some bug fixes as well that will probably resolve this issue (especially the wget module).

**Comment by ChrisWiegman** [comment]
Updated all modules but now getting the following:

Error: Duplicate declaration: File[/usr/bin/mailhog] is already declared in file /tmp/vagrant-puppet/modules-ac4bee6c01c8d2f6b4bf0d528a6ddcfc/mailhog/manifests/install.pp:36; cannot redeclare at /tmp/vagrant-puppet/modules-ac4bee6c01c8d2f6b4bf0d528a6ddcfc/wget/manifests/fetch.pp:200 on node pv
==> default: Error: Duplicate declaration: File[/usr/bin/mailhog] is already declared in file /tmp/vagrant-puppet/modules-ac4bee6c01c8d2f6b4bf0d528a6ddcfc/mailhog/manifests/install.pp:36; cannot redeclare at /tmp/vagrant-puppet/modules-ac4bee6c01c8d2f6b4bf0d528a6ddcfc/wget/manifests/fetch.pp:200 on node pv

**Comment by ftaeger** [comment]
Seems like this is the case while updating the Mailhog module. Seems to be ok for fresh installs. I will take a closer look asap...

**Comment by ChrisWiegman** [comment]
@ftaeger Were you ever able to make any progress on this one?

**Comment by ftaeger** [comment]
I incorporated the changed from jeffgeorge. Could you please test the module in version 1.1.0?

**Comment by ChrisWiegman** [comment]
Looks like all is working now. Thank you.
