### ISSUE TITLE
Debian Jessie needs proper rights for /usr/local and /usr/local/bin

### ISSUE THREAD

**Issue by cdoublev** [ftaeger/ftaeger-mailhog#7]
I know `ftaeger/mailhog` is currently tested only for Ubuntu 14.04 and 12.04. I managed to make it work on Debian Jessie 8.6 with a simple tweak, but I'm not sure it has no side effect.

The Mailhog API was not listening on port 8025. Output from `service mailhog status` was showing this error: 

> daemon: fatal: refusing to execute unsafe program: /usr/bin/mailhog (/usr/local/bin is group writable)

I changed rights for `/usr/local/bin` then for `/usr/local` with `chmod g-w /usr/local(/bin)` and I restarted mailhog service. It worked, but like I said, I don't know if some groups users usually needs to write things in these directories 

I hope it could help someone using this module on Debian. Feel free to close this issue.

**Comment by ftaeger** [comment]
Feel free to commit a code snippet ... I am not actively working on this module anymore...
