### ISSUE TITLE
Unknown variable: 'mailhog::params::wget_cache_dir'

### ISSUE THREAD

**Issue by tdm4** [ftaeger/ftaeger-mailhog#8]
I noticed it's defined here in init.pp:
https://github.com/ftaeger/ftaeger-mailhog/blob/master/manifests/init.pp#L79

But it doesn't exist anywhere else, nor is it used for anything. Perhaps line 79 should be deleted from init.pp?

**Comment by jeffgeorge** [comment]
Rather than scrub the parameter, I stubbed it out in `params.pp`. Equally simple change, non-destructive, and now if somebody actually wants to define a cache directory for wget the parameter is ready to implement.
